our-courses_reviews_img
NataliaIvasiv/our-first-team-project pull request #9
Opened 2023-11-04 08:55 UTC by Oksana2020LA

our-courses_reviews_img - ready

2023-11-04 21:32 UTC, NataliaIvasiv commented on src/css/our-courses.css
> +@media screen and (max-width: 767.98px) {
якась дивна max-width.
чому не 768?

2023-11-04 21:34 UTC, NataliaIvasiv commented on src/css/our-courses.css
> +    .container {
клас .container є у reset. Тобто вам не потрібно його вже прописувати в css, просто додаєте його у свій html на відповідну секцію. тут його треба забрати.

2023-11-04 21:35 UTC, NataliaIvasiv commented on src/css/our-courses.css
> +    letter-spacing: -.02em;
тут поправте: 
letter-spacing: -0.02em;

2023-11-04 21:36 UTC, NataliaIvasiv commented on src/css/our-courses.css
> +    font-weight: 400;
поддивіться стилі для body. вони такі самі. тобто це все наслідується. непотрібно їх ще раз писати

2023-11-04 21:43 UTC, NataliaIvasiv commented on src/css/our-courses.css
> +        width: calc((100%-40px) / 3);
тут чомусь формула не спрацьовує.. треба подумати

2023-11-04 21:45 UTC, NataliaIvasiv approved these changes
внесіть, будь ласка, зміни прописані в коментарях.

2023-11-04 21:47 UTC, NataliaIvasiv requested changes
я підтверджу ваш ріквест, коли ви внесете зміни :-)

2023-11-05 03:28 UTC, Oksana2020LA commented on src/css/our-courses.css
> +@media screen and (max-width: 767.98px) {
Указання розмірів в @media запитах з точністю до 0.02px зазвичай виникає в результаті прагнення уникнути конфліктів між різними пристроями з різними роздільними здатностями екранів. Зазначення 767.98px замість 768px може бути наслідком обчислень, пов'язаних з піксельною щільністю (pixel density) екранів та масштабуванням.

Деякі пристрої мають високу щільність пікселів, через що 1px на таких пристроях може виглядати як дрібний інтервал на екрані. Це може вплинути на реальні розміри контенту, які відображаються на екрані, і може бути важливим у дизайні, який потребує високої точності.

Деякі розробники включають дрібніші діапазони для забезпечення більшої точності та адаптабельності при масштабуванні на різних пристроях. Це дозволяє краще управляти різними розмірами екранів і забезпечує більш гнучкий та точний дизайн для широкого спектру пристроїв.

2023-11-05 07:20 UTC, NataliaIvasiv commented on src/css/our-courses.css
> +@media screen and (max-width: 767.98px) {
дякую, переконали)

2023-11-05 19:09 UTC, closed without merging